version: 0.2
run-as: root


phases:
  pre_build:
    commands:
      - echo copying environment variables...
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 664697292925.dkr.ecr.us-east-1.amazonaws.com      
      - REPOSITORY_URI=664697292925.dkr.ecr.us-east-1.amazonaws.com/api-node
      - IMAGE_TAG=latest
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_HASH=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 664697292925.dkr.ecr.us-east-1.amazonaws.com
      - echo era  pra dar o build...
      - docker build -t api-node .
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 664697292925.dkr.ecr.us-east-1.amazonaws.com
      - docker tag api-node:latest 664697292925.dkr.ecr.us-east-1.amazonaws.com/api-node:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 664697292925.dkr.ecr.us-east-1.amazonaws.com
      - docker push 664697292925.dkr.ecr.us-east-1.amazonaws.com/api-node:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' api-node-container $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json
      - echo Build completed on `date`
artifacts:
    files: imagedefinitions.json
