version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo Removing unnecessary files...
      - rm -rf node_modules/
      - echo Build completed on `date`

artifacts:
  base-directory: '.'
  files:
    - '**/*'
