version: '3.9'
services:
  server:
    container_name: node.api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '7941:7941'
    volumes:
      - '.:/app'
    command: ' yarn start'
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 1000M
